title: hhwyt
subtitle: The life of a frustrated engineer

url: "https://hhwyt.github.io"
baseurl: "/"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://hhwyt.github.io/resume.pdf"
